<?php

namespace restauranteBundle\Repository;

/**
 * tapasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tapasRepository extends \Doctrine\ORM\EntityRepository
{
}
