usuario:
    resource: "@usuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

restaurante:
    resource: "@restauranteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
